name = "karn pack"
author = "Lenny"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e480b1d2f4bddeac2b4cd051862f7126f416659f46e502e7683018e40f065d66"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
datapack-folder = "datapacks"
