name = "karn pack"
author = "Lenny"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed829c976ec954a9bfb8b16ae765d7d8f53574984338536fba41bb2d731f70fb"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
datapack-folder = "datapacks"
