name = "karn pack"
author = "Lenny"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fa6b73c998821ad627b4711f8d19b2901d46c8ad60089a6e940e4b61d21426f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
datapack-folder = "datapacks"
